1. NumPy is a Python library used for working with arrays.


2. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.


3. NumPy stands for Numerical Python.

4. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.


In [ ]:
pip install numpy

In [2]:
# Importing necessary libraries
import numpy as np
import pandas as pd

In [8]:
print(np.__version__)

2.2.2


0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [9]:
arr = np.array(42)

print(arr)

42


An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [10]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


An array that has 1-D arrays as its elements is called a 2-D array.



In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
"""A tensor is a multidimensional array — kind of like a generalization of scalars, vectors, and matrices.


1. scalar   5   tensor rank -0
2. vector [1,2,3]   tensor rank 1
3. matrix [[1,2],[3,4]]  TRank- 2
4. 3D Tensor [[[1],[2],[3],[4]]]  Tensor rank -3
5. n-D Tensor	magine a 4D+ array, like an image batch in   deep learning   4+

"""

'A tensor is a multidimensional array — kind of like a generalization of scalars, vectors, and matrices.\n\n\n1. scalar   5   tensor rank -0\n2. vector [1,2,3]   tensor rank 1\n3. matrix [[1,2],[3,4]]  TRank- 2\n4. 3D Tensor [[[1],[2],[3],[4]]]  Tensor rank -3\n5. n-D Tensor\tmagine a 4D+ array, like an image batch in   deep learning   4+\n\n'

In [3]:
# ----------------------------
# NumPy Section
# ----------------------------

print("===== NumPy Examples =====")

# 1. Creating NumPy arrays
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

arr2 = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr2)

===== NumPy Examples =====
1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]


In [4]:

# 2. Array operations
print("Array Sum:", arr1 + 5)
print("Element-wise Addition:", arr1 + arr1)
print("Mean of arr1:", np.mean(arr1))
print("Reshape 1D to 2D:\n", arr1.reshape((2, 2)))

Array Sum: [6 7 8 9]
Element-wise Addition: [2 4 6 8]
Mean of arr1: 2.5
Reshape 1D to 2D:
 [[1 2]
 [3 4]]


In [ ]:
# 3. Useful functions
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

random_arr = np.random.randint(1, 10, size=(3, 3))
print("Random Integer Array:\n", random_arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Random Integer Array:
 [[6 4 5]
 [5 6 4]
 [3 8 9]]


In [15]:
# Get the first element from the following array:


arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[2] + arr[3])


1
7


In [17]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('Last element from 2nd dim: ', arr[1, -1])


2nd element on 1st row:  2
Last element from 2nd dim:  10


i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [18]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [20]:
arr = np.array(['Apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [28]:
np.zeros((2, 3))
np.ones((3, 3))
np.eye(3)  # Identity matrix
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(2, 2)


array([[0.93604269, 0.60633199],
       [0.72912919, 0.44017949]])

In [29]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
reshaped = arr.reshape(2, 3)
flattened = arr.flatten()
transposed = arr.T


In [30]:
a = np.array([10, 20, 30, 40])
print(a[0])     # 10
print(a[-1])    # 40
print(a[1:3])   # [20 30]

matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix[1, 1])  # 4
print(matrix[:, 0])  # First column


10
40
[20 30]
4
[1 3 5]


In [31]:
a = np.array([5, 10, 15, 20])
print(a[a > 10])   # [15 20]


[15 20]


In [32]:
np.unique([1, 2, 2, 3])
np.sort([3, 1, 2])
np.concatenate([np.array([1, 2]), np.array([3, 4])])

array([1, 2, 3, 4])

In [33]:

arr = np.random.randint(1, 101, (5, 5))
print("Array:\n", arr)
print("Mean:", np.mean(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Std Dev:", np.std(arr))


Array:
 [[65 15 93 98 32]
 [85 11  3 33 86]
 [65 19 85 59 29]
 [61 99 89 34 75]
 [36 20 78 92 31]]
Mean: 55.72
Min: 3
Max: 99
Std Dev: 30.666620289820003
